# Generated by Django 6.0.3 on 2026-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_looping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_shuffled',
            field=models.BooleanField(default=False),
        ),
    ]
