# Generated by Django 6.0.3 on 2026-03-21 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Завершено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='ФИО'),
        ),
    ]
