# Generated by Django 6.0.3 on 2026-03-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='master_volume',
            field=models.FloatField(default=1.0),
        ),
    ]
