# Generated by Django 6.0.3 on 2026-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_message_state_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
