# Generated by Django 5.2.8 on 2026-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_message_state_alter_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
